### DCF MERGE FILE
# MEDIAS
setwd("C:/Users/f.masnadi/Desktop/BIOLOGIA della PESCA/UGS_RACCOLTA_DATI/DATA_CALL/MEDIAS_2019")
library(dplyr)
library(readr)

##### ITA_ABUND_BIOM
ITA_ABUND_BIOM17 <- read_csv("ITA_ABUND_BIOM17.csv")
ITA_ABUND_BIOM_GSAs_9_10_16 <- read_csv("ITA_ABUND_BIOM_GSAs 9 10 16.csv")
str(ITA_ABUND_BIOM17)
str(ITA_ABUND_BIOM_GSAs_9_10_16)

ITA_ABUND_BIOM17 <- ITA_ABUND_BIOM17 %>% mutate(NAME_OF_SURVEY =  replace(NAME_OF_SURVEY, NAME_OF_SURVEY == "MEDIAS", "MS"))

ITA_ABUND_BIOM<-rbind(ITA_ABUND_BIOM17, ITA_ABUND_BIOM_GSAs_9_10_16)
ITA_ABUND_BIOM[is.na(ITA_ABUND_BIOM)]<-0 # replace di 0 con NA
write_csv( ITA_ABUND_BIOM,"ITA_ABUND_BIOM.csv")

##### ITA_ABUNDANCE
ITA_ABUNDANCE17 <- read_csv("ITA_ABUNDANCE17.csv")
ITA_ABUNDANCE_GSAs_9_10_16 <- read_csv("ITA_ABUNDANCE_GSAs 9 10 16.csv")
str(ITA_ABUNDANCE17);head(ITA_ABUNDANCE17)
str(ITA_ABUNDANCE_GSAs_9_10_16)

ITA_ABUNDANCE17 <- ITA_ABUNDANCE17 %>% mutate(NAME_OF_SURVEY =  replace(NAME_OF_SURVEY, NAME_OF_SURVEY == "MEDIAS", "MS"))

ITA_ABUNDANCE<-rbind(ITA_ABUNDANCE17, ITA_ABUNDANCE_GSAs_9_10_16)
ITA_ABUNDANCE[is.na(ITA_ABUNDANCE)]<-0 # replace di 0 con NA
write_csv( ITA_ABUNDANCE,"ITA_ABUNDANCE.csv")

##### ITA_BIOMASS
ITA_BIOMASS17 <- read_csv("ITA_BIOMASS17.csv")
ITA_BIOMASS_GSAs_9_10_16 <- read_csv("ITA_BIOMASS_GSAs 9 10 16.csv")
str(ITA_BIOMASS17);head(ITA_BIOMASS17)
str(ITA_BIOMASS_GSAs_9_10_16)

ITA_BIOMASS17 <- ITA_BIOMASS17 %>% mutate(NAME_OF_SURVEY =  replace(NAME_OF_SURVEY, NAME_OF_SURVEY == "MEDIAS", "MS"))

ITA_BIOMASS<-rbind(ITA_BIOMASS17, ITA_BIOMASS_GSAs_9_10_16)
ITA_BIOMASS[is.na(ITA_BIOMASS)]<-0 # replace di 0 con NA
write_csv( ITA_BIOMASS,"ITA_BIOMASS.csv")
